### PR TITLE
Fix/ADF-1191/Double slash in criteria

### PR DESCRIPTION
**Pull request by jsconan**
### Summary

Fix the visual glitch in the list of criteria: a double slash was added to each duplicated property.

### Details

Remove the duplicated slash.
Also, fix a bad design with inlined HTML templates.

### How to test
-  compile the code
    ```sh
    npm run build:all
    ```
-  run the unit tests
    ```sh
    npm run test:keepAlive
    ```
    Open the browser at: http://127.0.0.1:5400/test/searchModal/advancedSearch/test.html
    Play with the criteria. No more double slashes should show up.
- checkout the branch in `tao/views/node_module/@oat-sa/tao-core-ui`, and check the advanced search in TAO (you will need to also checkout the integration branches in the other repositories)

### CODE REVIEW

**Review by bziondik — CHANGES_REQUESTED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

Please, check unit test
image

**Review by bziondik — APPROVED** [review]
Forgot to build before, all tests passed
image

**Comment by shaveko** [comment]
Looks nice, 

I've found a small issue with highlighting the rows. 

(null) symbols are being highlighted although they are not taken into account while search is performed
Screenshot (2)

**Comment by jsconan** [comment]
Thank you @shaveko for the notice. I was only fixing the double slash, but in the meantime, I wanted to clean the code a bit. The highlight was already behaving wrong before.

I took time to rework this part too:
- as the search only applies to the main label, I removed the highlight in the alias and in the class label
- I unified the templates so that they look similar
- I fixed the dummy `null` issue too

**Pull request merged**
