### PR TITLE
[Fix] - ADF-7 - Replace OR with AND in Advanced search criteria 

### PR DESCRIPTION
**Pull request by 404passionFruit**
**Jira**
https://oat-sa.atlassian.net/browse/ADF-7

**TL;DR**
This is a temp solution.
In order for advanced search to work with criteria when multiple values are chosen the team decided to replace OR operator with AND in search request. This is due to some BE limitations with Elastic. Fix of OR operator is in backlog so we need to go with AND for now.

**Deployed** to playground, link is in the ticket

### CODE REVIEW

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Comment by bziondik** [comment]
Please, check failed unit tests on CI 
image

**Comment by habemuscode** [comment]
Test are failing because `instance.getState()` doesn't return anything. Variable is outside of scope

**Review by AnastasiaArcadia — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by bziondik — APPROVED** [review]

**Review by AnastasiaArcadia — APPROVED** [review]

**Pull request merged**
