### PR TITLE
chore: migrate build to github actions

### PR DESCRIPTION
**Pull request by krampstudio**
Related to https://oat-sa.atlassian.net/browse/RO-571 (since it's blocking the review)

 - upgrade some dev tools 
 - migrate to github action to the following checks in CI:
   - conventional commits
   - unit test
   - coverage
   - eslint 
 - fix broken unit tests 
   - the issue with the previewer is that puppeteer doesn't support reading audio or video when headless
   - the issue with the taskQueueButton test was a code change without updating the test case 

Eslint report job fails because the repo contains too many lint errors, it's not blocking for PRs but highlights the changes required.

### CODE REVIEW

**Review by bziondik — CHANGES_REQUESTED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful
Have timeouts for random tests, but test from PR are passing
image

Failing `test/pageStatus/test.html`
image

**Comment by krampstudio** [comment]
> Have timeouts for random tests, but test from PR are passing

Which node version are you using. I have the feeling it's linked

**Comment by bziondik** [comment]
> > Have timeouts for random tests, but test from PR are passing
> 
> Which node version are you using. I have the feeling it's linked

I have v10.21.0

**Review by jsconan — APPROVED** [review]
Nice job!

Actually, I also have test failing in timeout randomly. I checked with different versions of node: `12.22.5` and `14.17.5`. The result was similar.

In fact, this is a known issue that nobody had time to tackle so far as you can see here: https://oat-sa.atlassian.net/browse/TR-1196
We can workaround it locally by tweaking the number of parallels tests: `PARALLEL_TESTS=1 npx qunit-testrunner`

But then it may also depend on the machine that performs the tests, which may take too long to process them. The issue is less visible on the CI.

**Review Checklist**
- [ ] ~~New code is covered by tests (if applicable)~~
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] ~~Changelog is updated according to changes (if applicable)~~
- [ ] ~~Documentation is updated according to changes (if applicable)~~

**Comment by oatymart** [comment]
Still unable to get passing tests for this repo in Github's CI. They need some development attention, so I still have doubts to merge the PR in current state.

**Comment by krampstudio** [comment]
I've increased the timeout of the failing tests. This is playing with popups to trigger the page visibility API.  My guess is that popup loading in puppeteer takes more or less time based on the env. I've tried many times and with the new timeouts, it didn't failed.

**Comment by oatymart** [comment]
It seems good to me, as the CI tests now pass. LGTM!

**Pull request merged**
