### PR TITLE
[Fix - ADF 249]: UDIR GenerisSearch: User gets "get?ClassUri" cancelled request in browser console with error pop-up message after clicking 'Clear' in Modal View.

### PR DESCRIPTION
**Pull request by habemuscode**
**Next PR after merge this**

https://github.com/oat-sa/tao-core/pull/2860

**Issue**

https://oat-sa.atlassian.net/browse/ADF-249

**Description**

Whenever the user is clicking the 'Clear' button in Modal View and then closes the Modal window, there's a loading process on the page with the common loading bar under the panel with tabs 'Items', 'Tests' etc. 
During this loading, the page is irresponsive to any interaction. After the timeout of 30 seconds, there's an error pop-up message appears and canceled the "get?ClassUri" request in the networking tab of DevTools.

**Steps to reproduce**

- Go to the Items/Tests/Assets tab.
- Click the Search icon.
- In opened Modal view window click the 'Clear' button.
- Close the Modal view.

**Actual result**

The page is unresponsive during loading and after the timeout of 30 seconds, there's an error pop-up message that appears and canceled the "get?ClassUri" request in the networking tab of DevTools.

**Expected result**

The modal window is closed and the page is available to interact with, no errors appear.

### CODE REVIEW

**Review by gabrielfs7 — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by adriloma — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] bumping versions are applied (if applicable)

**Review by AnastasiaArcadia — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] bumping versions are applied (if applicable)

**Comment by habemuscode** [comment]
Temporary deployed here:  http://test-as-acl-fix.playground.kitchen.it.taocloud.org:44291

**Review by 404passionFruit — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable) - tested on Kitchen
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] bumping versions are applied (if applicable)

**Pull request merged**
