### PR TITLE
fix: collapsing lines when whole text is <sub> or <sup>

### PR DESCRIPTION
**Pull request by yukipastelcat**
# Pull request summary

Related to [OATSD-1881](https://oat-sa.atlassian.net/browse/OATSD-1881).

Removed `line-height: 0;`, so when `<sub>` or `<sup>` elements take more than one line text wouldn't collapse to a single one.

# How to test

This fix needs to be tested within Item Result Preview.

1. Setup new dockerized TAO instance as described in [docker-stack-cli](https://github.com/oat-sa/docker-stack-cli)
2. Publish `@oat-sa/tao-core-ui` package to your local [Verdaccio](https://verdaccio.org/) instance or to a file and update dependency within your package-tao (`tao/views`) or update it directly from this branch (`npm i github:oat-sa/tao-core-ui-fe#fix/OATSD-1881/sub-line-height`) and rebuild css by running `npx run taosass` from `tao/views/build`
3. Create and take the test with ExtendedTextInteraction (it's important to select whole text and make it `sub` or `sup` by clicking corresponding button)
4. Login as admin, open developer tools with Network tab, go to results screen and look for `/getResults` request, then go to response preview tab and look for `data[0].id` value - you'll have to encode this value via `encodeURIComponent` in console and use as `resultId` in the Launch URL
5. Use the following tool http://ltiapps.net/test/tc.php to open Item Result Previewer. Your Launch URL should look something like `https://<your-tao-instance>.docker.localhost/ltiOutcomeUi/ItemResultPreviewer/launch?itemRef=<itemRef>&resultId=<resultId>` (I'm not sure how to find itemRef, so I ended up using default name for my item and itemRef for it was `item-1`)
6. Then fill Consumer key and Shared secret values, click save data and Launch TP in new window - `<sub>` or `<sup>` lines shouldn't be collapsed

### CODE REVIEW

**Comment by btamas** [comment]
What is the purpose of this PR?
1. It is a fix in the recent code? In this case, why should I test it in an old Sprint 147 code?
2. It is a fix backport? In this case, why is the target `develop`?

**Comment by yukipastelcat** [comment]
@btamas this is not a fix in the recent code, I just provided an environment from OATSD-1881 ticket that's why it's Sprint 147, the fix is not a backport, it's a fix for a problem, that was presented long time ago (`line-height: 0;` causes text lines to collapse)

**Comment by btamas** [comment]
> @btamas this is not a fix in the recent code,

It is, if you merge this code to `develop` branch.

> I just provided an environment from OATSD-1881 ticket that's why it's Sprint 147, the fix is not a backport, it's a fix for a problem, that was presented long time ago (`line-height: 0;` causes text lines to collapse)

But it should be backported if we would like to deploy this fix to the client that uses Sprint 147.

**Comment by yukipastelcat** [comment]
@btamas issue is present on latest `develop`, that's why this PR is targeting this branch, and yes, this fix needs to be backported to Sprint 147

**Review by btamas — APPROVED** [review]
It works for me.
Screen Shot 2022-05-30 at 11 03 45

What I don't know is, why was it added? Won't it create an issue somewhere else? I found some `<sub>` and `<sup>` tags in MathEntry and Calculator, but they look good after the fix.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Comment by yukipastelcat** [comment]
> It works for me. Screen Shot 2022-05-30 at 11 03 45
> 
> What I don't know is, why was it added? Won't it create an issue somewhere else? I found some `<sub>` and `<sup>` tags in MathEntry and Calculator, but they look good after the fix.

It was probably added as a fix for `<sub>` and `<sup>` affecting line heights (see https://stackoverflow.com/a/6594576/7181962), but it doesn't seem to do so anymore

**Pull request merged**
