### PR TITLE
Prevent the datatable to fail if the element has been removed

### PR DESCRIPTION
**Pull request by krampstudio**
Related to https://oat-sa.atlassian.net/browse/RO-571

Quick fix to prevent the datatable component to just fail if the element has been removed while querying.

Please note, if the element is removed the `error` event will not be 

How to test:
 - Run the unit test locally
 - In the authoring, Test Center extension, click the "save" quickly 
   - Without this fix the datatable  on the removed element will try to render if the xhr is still running after the element removal
   - Without this fix the datatable  does not render if the element is removed or doesn't have the datatable data linked

### CODE REVIEW

**Comment by yukipastelcat** [comment]
Which Node.js version do I use to run unit tests locally? I'm using 14.17.0 currently and it looks like tests are hanging:
image
And in VSCode terminal they're exiting with this log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin/node',
1 verbose cli   '/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle @oat-sa/tao-core-ui@1.35.0~pretest: @oat-sa/tao-core-ui@1.35.0
6 info lifecycle @oat-sa/tao-core-ui@1.35.0~test: @oat-sa/tao-core-ui@1.35.0
7 verbose lifecycle @oat-sa/tao-core-ui@1.35.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle @oat-sa/tao-core-ui@1.35.0~test: PATH: /Users/kirill.sedunov/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/kirill.sedunov/Documents/Repositories/tao-core-ui-fe/node_modules/.bin:/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin:/Users/kirill.sedunov/dev/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/kirill.sedunov/opt/miniconda3/bin:/Users/kirill.sedunov/opt/miniconda3/condabin:/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin:/Users/kirill.sedunov/dev/flutter/bin:/Users/kirill.sedunov/.dotnet/tools:/Users/kirill.sedunov/.dotnet/tools
9 verbose lifecycle @oat-sa/tao-core-ui@1.35.0~test: CWD: /Users/kirill.sedunov/Documents/Repositories/tao-core-ui-fe
10 silly lifecycle @oat-sa/tao-core-ui@1.35.0~test: Args: [ '-c', 'npx qunit-testrunner' ]
11 silly lifecycle @oat-sa/tao-core-ui@1.35.0~test: Returned: code: 1  signal: null
12 info lifecycle @oat-sa/tao-core-ui@1.35.0~test: Failed to exec test script
13 verbose stack Error: @oat-sa/tao-core-ui@1.35.0 test: `npx qunit-testrunner`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid @oat-sa/tao-core-ui@1.35.0
15 verbose cwd /Users/kirill.sedunov/Documents/Repositories/tao-core-ui-fe
16 verbose Darwin 20.6.0
17 verbose argv "/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin/node" "/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin/npm" "run" "test"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error @oat-sa/tao-core-ui@1.35.0 test: `npx qunit-testrunner`
22 error Exit status 1
23 error Failed at the @oat-sa/tao-core-ui@1.35.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by krampstudio** [comment]
> Which Node.js version do I have to use to run unit tests locally? I'm using 14.17.0 currently and it looks like tests are hanging:
> image
> And in VSCode terminal they're exiting with this log:
> 
> ```
> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   '/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin/node',
> 1 verbose cli   '/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'test'
> 1 verbose cli ]
> 2 info using npm@6.14.13
> 3 info using node@v14.17.0
> 4 verbose run-script [ 'pretest', 'test', 'posttest' ]
> 5 info lifecycle @oat-sa/tao-core-ui@1.35.0~pretest: @oat-sa/tao-core-ui@1.35.0
> 6 info lifecycle @oat-sa/tao-core-ui@1.35.0~test: @oat-sa/tao-core-ui@1.35.0
> 7 verbose lifecycle @oat-sa/tao-core-ui@1.35.0~test: unsafe-perm in lifecycle true
> 8 verbose lifecycle @oat-sa/tao-core-ui@1.35.0~test: PATH: /Users/kirill.sedunov/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/kirill.sedunov/Documents/Repositories/tao-core-ui-fe/node_modules/.bin:/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin:/Users/kirill.sedunov/dev/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Users/kirill.sedunov/opt/miniconda3/bin:/Users/kirill.sedunov/opt/miniconda3/condabin:/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin:/Users/kirill.sedunov/dev/flutter/bin:/Users/kirill.sedunov/.dotnet/tools:/Users/kirill.sedunov/.dotnet/tools
> 9 verbose lifecycle @oat-sa/tao-core-ui@1.35.0~test: CWD: /Users/kirill.sedunov/Documents/Repositories/tao-core-ui-fe
> 10 silly lifecycle @oat-sa/tao-core-ui@1.35.0~test: Args: [ '-c', 'npx qunit-testrunner' ]
> 11 silly lifecycle @oat-sa/tao-core-ui@1.35.0~test: Returned: code: 1  signal: null
> 12 info lifecycle @oat-sa/tao-core-ui@1.35.0~test: Failed to exec test script
> 13 verbose stack Error: @oat-sa/tao-core-ui@1.35.0 test: `npx qunit-testrunner`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:376:20)
> 13 verbose stack     at ChildProcess.<anonymous> (/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:376:20)
> 13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> 14 verbose pkgid @oat-sa/tao-core-ui@1.35.0
> 15 verbose cwd /Users/kirill.sedunov/Documents/Repositories/tao-core-ui-fe
> 16 verbose Darwin 20.6.0
> 17 verbose argv "/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin/node" "/Users/kirill.sedunov/.nvm/versions/node/v14.17.0/bin/npm" "run" "test"
> 18 verbose node v14.17.0
> 19 verbose npm  v6.14.13
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error @oat-sa/tao-core-ui@1.35.0 test: `npx qunit-testrunner`
> 22 error Exit status 1
> 23 error Failed at the @oat-sa/tao-core-ui@1.35.0 test script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
> ```

For this repo I've used node 10 and some unralted tests were failing that I fixed in https://github.com/oat-sa/tao-core-ui-fe/pull/363 
(I think we should merge that pr first to confirm tests are passing in this one)

**Review by bziondik — APPROVED** [review]
- [x]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful
image

**Review by yukipastelcat — APPROVED** [review]
Codewise everything looks good, I tried building it, replacing dist on my local instance - and it works

- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Documentation updated

**Pull request merged**
