### PR TITLE
[Fix] CON 122 - Graphic design match mockup

### PR DESCRIPTION
**Pull request by habemuscode**
**Issues**

https://oat-sa.atlassian.net/browse/CON-122

**Related issues**

https://github.com/oat-sa/extension-tao-itemqti/pull/1600

**Mockup**

https://projects.invisionapp.com/d/main#/console/20371039/431571617/preview

**Fix**

- [x] **4. Criteria dropdown**: use a 4px padding-top for class="select2-search" .
- [x] **8. Add criteria button (in advance search)**: spacing between icon and label. Use the same look and feel as for the add choice button for drop downs.
- [x] **5. Inputs field/dropdown**: Properly vertically align the folder and search icon inside the respective field.
- [x] **Input field/dropdown**: Tint down the icons to #666
- [x] **Bonus**: Center the icon

**Before**

- 8 imagen
- 4 imagen
- 5 imagen
- 6 imagen
- 2 imagen
- 2.1 (on focus) imagen

**After**

- 8 imagen
- 4 imagen
- 5 imagen
- 6 imagen
- 2 imagen
- 2.1 (on focus) imagen

### CODE REVIEW

**Review by andrey-ponamarev — CHANGES_REQUESTED** [review]
Bump version is missing

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Comment by bziondik** [comment]
Please, update version

**Comment by habemuscode** [comment]
Merged develop and pushed version, sorry

**Review by gabrielfs7 — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by andrey-ponamarev — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

**Comment by habemuscode** [comment]
Can be tested here: http://playground.kitchen.it.taocloud.org/?p=test-juan_delivery.git;a=summary

**Pull request merged**
