### PR TITLE
[Fix] TAO 7321 - Media sizer not correspond size

### PR DESCRIPTION
**Pull request by habemuscode**
**NOTE: For test all functionality needs this other PR**

https://github.com/oat-sa/tao-item-runner-qti-fe/pull/110

**Related to**

https://oat-sa.atlassian.net/browse/TAO-7321

**Description**

- Create Item.
- Add media interaction and select video for content.
- Try to change content size Width from ~1000 to ~100.

### CODE REVIEW

**Review by btamas — APPROVED** [review]

**Review by bziondik — APPROVED** [review]
Code review only
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by andrey-ponamarev — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

**Review by bziondik — CHANGES_REQUESTED** [review]
Please, check height of media-player never changes.

**Comment by habemuscode** [comment]
Was fixed by @bziondik in other PRs

**Pull request closed without merging**
