### PR TITLE
Fix/ADF-1191/Persist sorted columns

### PR DESCRIPTION
**Pull request by jsconan**
### Summary

Store the sort options together with the search result.

### Details

The search results are stored in the local storage to speed up the next visit to the search modal. If the results were sorted, they are restored sorted. However, the sort indicator was not restored too.

### How to test
-  compile the code
    ```sh
    npm run build:all
    ```
-  run the unit tests
    ```sh
    npm run test:keepAlive
    ```
    Open the browser at:
    - http://127.0.0.1:5400/test/searchModal/advancedSearch/test.html
    - http://127.0.0.1:5400/test/searchModal/test.html
- checkout the branch in `tao/views/node_module/@oat-sa/tao-core-ui`, and check the advanced search in TAO (you will need to also checkout the integration branches in the other repositories)

### CODE REVIEW

**Review by bziondik — CHANGES_REQUESTED** [review]
In unit test, when edit search word and then click again Search, after rerender of table, see 2 manage columns links
image

**Comment by jsconan** [comment]
Thank you @bziondik ! I'also noticed the issue while working on the next correction. And I found the root cause. The DOM is polluted by the datatable, even after having emptied the container. I restored the previous approach with the recreation of the container, but keeping the HTML template outside of the code.

**Review by bziondik — APPROVED** [review]
- [x]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by shaveko — APPROVED** [review]
Looks good! Codewise and tests (unit and visual looks cool)

Looking forward to check deployed version

**Pull request merged**
